package com.amrhishammahmoud.rahhal.models

import android.content.Context
import com.amrhishammahmoud.rahhal.R


object ContinentsApiObject {

    fun continentsNames(context: Context): Array<String> {
        return arrayOf(
            context.getString(R.string.africa),
            context.getString(R.string.europe),
            context.getString(R.string.asia),
            context.getString(R.string.north_america),
            context.getString(R.string.south_america),
            context.getString(R.string.oceania),
            context.getString(R.string.antarctica)
        )
    }

    fun continentsMapsBackground(): Array<Int> {
        return arrayOf(
            R.drawable.africa_background,
            R.drawable.europe_background,
            R.drawable.asia_background,
            R.drawable.north_america_background,
            R.drawable.south_america_background,
            R.drawable.oceania_background,
            R.drawable.antarctica_background
        )
    }

}

object CountriesPicturesApiObject {
    fun countriesPictures(): Array<Int> {
        return arrayOf(
            R.drawable.togo_country,
            R.drawable.mayotte_country,
            R.drawable.georgia_country,
            R.drawable.vanuatu_country,
            R.drawable.kyrgyzstan_country,
            R.drawable.niger_country,
            R.drawable.china_countrry,
            R.drawable.tuvalu_country,
            R.drawable.comoros_countrry,
            R.drawable.bosnia_country,
            R.drawable.bahrain_country,
            R.drawable.somalia_country,
            R.drawable.saint_barthelemy_country,
            R.drawable.latvia_country,
            R.drawable.cayman_country,
            R.drawable.netherlands_country,
            R.drawable.lesotho_country,
            R.drawable.venezuela_country,
            R.drawable.kenya_country,
            R.drawable.turkey_country,
            R.drawable.fiji_country,
            R.drawable.trinidadandtobago_country,
            R.drawable.honduras,
            R.drawable.jersey,
            R.drawable.djibouti,
            R.drawable.reunion,
            R.drawable.eswatini,
            R.drawable.tajikistan,
            R.drawable.saudi_arabia,
            R.drawable.bermuda,
            R.drawable.newzaland,
            R.drawable.belarus,
            R.drawable.christmas_island,
            R.drawable.gambia,
            R.drawable.french_polynesia,
            R.drawable.congo,
            R.drawable.costareca,
            R.drawable.malawi,
            R.drawable.congo,
            R.drawable.oman,
            R.drawable.iraq,
            R.drawable.niue,
            R.drawable.senegal,
            R.drawable.lebanon,
            R.drawable.angola,
            R.drawable.iran,
            R.drawable.ecuador,
            R.drawable.laos,
            R.drawable.srilanka,
            R.drawable.aruba,
            R.drawable.sao_tome_and_principe,
            R.drawable.grenada,
            R.drawable.montserrat,
            R.drawable.western_sahara,
            R.drawable.guinea,
            R.drawable.british_virgin_islands,
            R.drawable.panama,
            R.drawable.yemen,
            R.drawable.estonia,
            R.drawable.guyana,
            R.drawable.luxembourg,
            R.drawable.namibia,
            R.drawable.kosovo,
            R.drawable.new_caledonia,
            R.drawable.saint_pierre_and_miquelon,
            R.drawable.libya,
            R.drawable.myanmar,
            R.drawable.mali,
            R.drawable.argentina,
            R.drawable.french_guiana,
            R.drawable.uganda,
            R.drawable.malaysia,
            R.drawable.zambia,
            R.drawable.micronesia,
            R.drawable.slovakia,
            R.drawable.burundi,
            R.drawable.serbia,
            R.drawable.turkmenistan,
            R.drawable.south_africa,
            R.drawable.kazakhstan,
            R.drawable.canada,
            R.drawable.poland,
            R.drawable.puerto_rico,
            R.drawable.cocos_islands,
            R.drawable.san_marino,
            R.drawable.american_samoa,
            R.drawable.qatar,
            R.drawable.gibraltar,
            R.drawable.croatia,
            R.drawable.svalbard_and_jan,
            R.drawable.isle_of_man,
            R.drawable.palastine,
            R.drawable.mauritius,
            R.drawable.saint_martin,
            R.drawable.sierra_lone,
            R.drawable.saint_kitts_and_nevis,
            R.drawable.iceland,
            R.drawable.heard_island_and_mcdonald_islands,
            R.drawable.kuwait,
            R.drawable.taiwan,
            R.drawable.cameron,
            R.drawable.el_salvador,
            R.drawable.macau,
            R.drawable.cuba,
            R.drawable.brazil,
            R.drawable.solomon_islands,
            R.drawable.greece,
            R.drawable.norway,
            R.drawable.jamaica,
            R.drawable.tanzania,
            R.drawable.bolivia,
            R.drawable.cyprus,
            R.drawable.mongolia,
            R.drawable.monaco,
            R.drawable.tunisia,
            R.drawable.antarctic_lands,
            R.drawable.syria,
            R.drawable.chile,
            R.drawable.azerbaijan,
            R.drawable.france,
            R.drawable.south_korea,
            R.drawable.ghana,
            R.drawable.danemark,
            R.drawable.sint_maarten,
            R.drawable.andorra,
            R.drawable.curacao,
            R.drawable.switzerland,
            R.drawable.north_macedonia,
            R.drawable.south_sudan,
            R.drawable.haiti,
            R.drawable.peru,
            R.drawable.guinea_bissau,
            R.drawable.czechia,
            R.drawable.portugal,
            R.drawable.gabon,
            R.drawable.mexico,
            R.drawable.italy,
            R.drawable.finland,
            R.drawable.zimbabwe,
            R.drawable.span,
            R.drawable.japan,
            R.drawable.seychelles,
            R.drawable.albania,
            R.drawable.moldova,
            R.drawable.guatemala,
            R.drawable.german,
            R.drawable.guadeloupe,
            R.drawable.bulgaria,
            R.drawable.paraguay,
            R.drawable.eritrea,
            R.drawable.sudan,
            R.drawable.equatorial_guinea,
            R.drawable.colombia,
            R.drawable.nigeria,
            R.drawable.montenegro,
            R.drawable.nepal,
            R.drawable.brunei,
            R.drawable.austria,
            R.drawable.turks_and_caicos_islands,
            R.drawable.bahamas,
            R.drawable.united_kingdom,
            R.drawable.british_indian_ocean_territory,
            R.drawable.liberia,
            R.drawable.anguilla,
            R.drawable.central_african,
            R.drawable.algeria,
            R.drawable.saint_lucia,
            R.drawable.romania,
            R.drawable.emirates,
            R.drawable.morroco,
            R.drawable.northern_mariana_islands,
            R.drawable.united_states_minor_outlying_islands,
            R.drawable.botswana,
            R.drawable.lithuania,
            R.drawable.caribbean_netherlands,
            R.drawable.cape_verde,
            R.drawable.usa,
            R.drawable.australia,
            R.drawable.guam,
            R.drawable.tonga,
            R.drawable.afghanistan,
            R.drawable.falkland,
            R.drawable.nauru,
            R.drawable.cook_islands,
            R.drawable.hungary,
            R.drawable.mauritania,
            R.drawable.slovenia,
            R.drawable.cchad,
            R.drawable.vatican,
            R.drawable.benin,
            R.drawable.singapore,
            R.drawable.malta,
            R.drawable.saint_vincent_and_the_grenadines,
            R.drawable.marshall,
            R.drawable.thailand,
            R.drawable.liechtenstein,
            R.drawable.ireland,
            R.drawable.maldives,
            R.drawable.vietnam,
            R.drawable.armenia,
            R.drawable.pakistan,
            R.drawable.ivory,
            R.drawable.russia,
            R.drawable.martinique,
            R.drawable.bouvet,
            R.drawable.timor_leste,
            R.drawable.nicaragua,
            R.drawable.papua_new_guinea,
            R.drawable.egypt,
            R.drawable.jordan,
            R.drawable.uruguay,
            R.drawable.burkina,
            R.drawable.cambodia,
            R.drawable.ethiopia,
            R.drawable.kiribati,
            R.drawable.bhutan,
            R.drawable.dominican,
            R.drawable.suriname,
            R.drawable.bangladesh,
            R.drawable.barbados,
            R.drawable.north_korea,
            R.drawable.greenland,
            R.drawable.belgium,
            R.drawable.palau,
            R.drawable.norfolk,
            R.drawable.georgia,
            R.drawable.philippines,
            R.drawable.india,
            R.drawable.indonesia,
            R.drawable.united_states_virgin_islands,
            R.drawable.rowanda,
            R.drawable.madagascar,
            R.drawable.hong_gong,
            R.drawable.samoa,
            R.drawable.faroe_islands,
            R.drawable.pitcairn,
            R.drawable.antigua,
            R.drawable.aland_islands,
            R.drawable.sweden,
            R.drawable.mozambique,
            R.drawable.uzbekistan,
            R.drawable.antarctica,
            R.drawable.wallis,
            R.drawable.ukraine,
            R.drawable.belize,
            R.drawable.saint_helena,
            R.drawable.guernsey,
            R.drawable.tokelau
        )
    }
}


object FamousApiObject {

    fun famousNames(): Array<String> {
        return arrayOf(
            "Eiffel Tower",
            "Statue of Liberty",
            "Colosseum",
            "Great Wall of China",
            "Pyramids of Giza",
            "Big Ben",
            "Taj Mahal",
            "Christ the Redeemer",
            "Sydney Opera House",
            "Hagia Sophia",
            "Mount Fuji",
            "Table Mountain",
            "Chichen Itza",
            "Machu Picchu",
            "Saint Basil’s Cathedral",
            "Sagrada Familia",
            "Angkor Wat",
            "Acropolis of Athens",
            "Burj Khalifa",
            "Registan",
            "Niagara Falls",
            "Borobudur",
            "Grand Palace",
            "Koutoubia Mosque",
            "Ha Long Bay"
        )
    }

    fun famousCountriesNames(): Array<String> {
        return arrayOf(
            "France",
            "USA",
            "Italy",
            "China",
            "Egypt",
            "United Kingdom",
            "India",
            "Brazil",
            "Australia",
            "Turkey",
            "Japan",
            "South Africa",
            "Mexico",
            "Peru",
            "Russia",
            "Spain",
            "Cambodia",
            "Greece",
            "United Arab Emirates",
            "Uzbekistan",
            "Canada/USA",
            "Indonesia",
            "Thailand",
            "Morocco",
            "Vietnam"
            )
    }

    fun famousCapitalsNames(): Array<String> {
        return arrayOf(
            "Paris",
            "New York City",
            "Rome",
            "Northern China",
            "Giza",
            "London",
            "Agra",
            "Rio de Janeiro",
            "Sydney",
            "Istanbul",
            "Near Tokyo",
            "Cape Town",
            "Yucatán Peninsula",
            "Andes Mountains",
            "Moscow (Red Square)",
            "Barcelona",
            "Siem Reap",
            "Athens",
            "Dubai",
            "Samarkand",
            "Border",
            "Central Java",
            "Bangkok",
            "Marrakech",
            "Quảng Ninh Province"
        )
    }

    fun famousImages(): Array<Int> {
        return arrayOf(
            R.drawable.eiffel,
            R.drawable.statue_of_liberty,
            R.drawable.colosseum,
            R.drawable.great_wall_of_china,
            R.drawable.pyramids,
            R.drawable.big_ben,
            R.drawable.tag_mahhal,
            R.drawable.christ_the_redeemer,
            R.drawable.sydney_opera_house,
            R.drawable.hagia_sophia,
            R.drawable.mount_fuji,
            R.drawable.table_mountain,
            R.drawable.chichen_itza,
            R.drawable.machu_picchu,
            R.drawable.saint_basil_cathedral,
            R.drawable.sagrada_familia,
            R.drawable.angkor_wat,
            R.drawable.acropolis,
            R.drawable.burj_khalifa,
            R.drawable.registan,
            R.drawable.niagra,
            R.drawable.borobudur,
            R.drawable.grand_palace,
            R.drawable.koutoubia,
            R.drawable.ha_long
        )
    }
}